version: '3.9'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "car"
      MYSQL_PASSWORD: "sharing"
      MYSQL_DATABASE: "carsharing"
    volumes:
      - "mysql:/var/lib/mysql"

volumes:
    mysql:
